# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainform.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1043, 858)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 90, 1001, 691))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout.setContentsMargins(10, 10, 10, 10)
        self.gridLayout.setSpacing(20)
        self.gridLayout.setObjectName("gridLayout")
        self.graphicsView_Green = PlotWidget(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.graphicsView_Green.setFont(font)
        self.graphicsView_Green.setObjectName("graphicsView_Green")
        self.gridLayout.addWidget(self.graphicsView_Green, 0, 1, 1, 1)
        self.graphicsView_White = PlotWidget(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.graphicsView_White.setFont(font)
        self.graphicsView_White.setObjectName("graphicsView_White")
        self.gridLayout.addWidget(self.graphicsView_White, 1, 1, 1, 1)
        self.graphicsView_Red = PlotWidget(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.graphicsView_Red.setFont(font)
        self.graphicsView_Red.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);")
        self.graphicsView_Red.setObjectName("graphicsView_Red")
        self.gridLayout.addWidget(self.graphicsView_Red, 0, 0, 1, 1)
        self.graphicsView_Blue = PlotWidget(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.graphicsView_Blue.setFont(font)
        self.graphicsView_Blue.setObjectName("graphicsView_Blue")
        self.gridLayout.addWidget(self.graphicsView_Blue, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(430, 20, 326, 51))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.dependence_IC = QtWidgets.QRadioButton(self.groupBox)
        self.dependence_IC.setGeometry(QtCore.QRect(85, 17, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dependence_IC.setFont(font)
        self.dependence_IC.setObjectName("dependence_IC")
        self.dependence_LI = QtWidgets.QRadioButton(self.groupBox)
        self.dependence_LI.setGeometry(QtCore.QRect(20, 17, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dependence_LI.setFont(font)
        self.dependence_LI.setChecked(True)
        self.dependence_LI.setObjectName("dependence_LI")
        self.dependence_LC = QtWidgets.QRadioButton(self.groupBox)
        self.dependence_LC.setGeometry(QtCore.QRect(175, 17, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dependence_LC.setFont(font)
        self.dependence_LC.setObjectName("dependence_LC")
        self.dependence_All = QtWidgets.QRadioButton(self.groupBox)
        self.dependence_All.setGeometry(QtCore.QRect(270, 17, 56, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dependence_All.setFont(font)
        self.dependence_All.setObjectName("dependence_All")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 20, 401, 51))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.comboBox_Port = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_Port.setGeometry(QtCore.QRect(10, 10, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_Port.setFont(font)
        self.comboBox_Port.setObjectName("comboBox_Port")
        self.pushButton_GO = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_GO.setGeometry(QtCore.QRect(265, 10, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_GO.setFont(font)
        self.pushButton_GO.setObjectName("pushButton_GO")
        self.comboBox_LED_Model = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_LED_Model.setGeometry(QtCore.QRect(130, 10, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_LED_Model.setFont(font)
        self.comboBox_LED_Model.setObjectName("comboBox_LED_Model")
        self.comboBox_LED_Model.addItem("")
        self.comboBox_LED_Model.addItem("")
        self.comboBox_LED_Model.addItem("")
        self.comboBox_LED_Model.addItem("")
        self.comboBox_LED_Model.addItem("")
        self.pushButton_GO_FAST = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_GO_FAST.setGeometry(QtCore.QRect(310, 10, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_GO_FAST.setFont(font)
        self.pushButton_GO_FAST.setObjectName("pushButton_GO_FAST")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setEnabled(True)
        self.progressBar.setGeometry(QtCore.QRect(770, 30, 266, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setStrikeOut(False)
        self.progressBar.setFont(font)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1043, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LED Test"))
        self.dependence_IC.setText(_translate("MainWindow", "I(Code)"))
        self.dependence_LI.setText(_translate("MainWindow", "L(I)"))
        self.dependence_LC.setText(_translate("MainWindow", "L(Code)"))
        self.dependence_All.setText(_translate("MainWindow", "All"))
        self.pushButton_GO.setText(_translate("MainWindow", "GO"))
        self.comboBox_LED_Model.setItemText(0, _translate("MainWindow", "WS2812b"))
        self.comboBox_LED_Model.setItemText(1, _translate("MainWindow", "WS2813"))
        self.comboBox_LED_Model.setItemText(2, _translate("MainWindow", "SK6812RGBW"))
        self.comboBox_LED_Model.setItemText(3, _translate("MainWindow", "SK9822"))
        self.comboBox_LED_Model.setItemText(4, _translate("MainWindow", "APA102"))
        self.pushButton_GO_FAST.setText(_translate("MainWindow", "GO FAST"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
